#!/usr/bin/env python3
"""
Pytest configuration and fixtures
"""

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from annex4parser.models import Base, Regulation, Rule

@pytest.fixture
def db_session():
    """Create a database session for testing"""
    engine = create_engine('sqlite:///:memory:')
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()
    
    try:
        yield session
    finally:
        session.close()

@pytest.fixture
def test_regulation(db_session):
    """Create test regulation data"""
    reg = Regulation(
        name='EU AI Act Test',
        version='1.0',
        source_url='https://example.com/ai-act',
        status='active'
    )
    db_session.add(reg)
    db_session.flush()
    
    # Create test rules
    test_rules = [
        {
            'section_code': 'Article9.2',
            'title': 'Risk Management System',
            'content': 'Providers of high-risk AI systems shall establish, implement, document and maintain a risk management system in relation to high-risk AI systems.'
        },
        {
            'section_code': 'Article10.1',
            'title': 'Data Governance',
            'content': 'Providers of high-risk AI systems shall ensure that the high-risk AI system is trained, validated and tested on data sets that meet the quality criteria.'
        },
        {
            'section_code': 'Article15.3',
            'title': 'Documentation Requirements',
            'content': 'Providers of high-risk AI systems shall draw up the technical documentation of the high-risk AI system.'
        },
        {
            'section_code': 'Article15.4',
            'title': 'Record Keeping',
            'content': 'Providers of high-risk AI systems shall keep the logs automatically generated by their high-risk AI systems.'
        },
        {
            'section_code': 'Article16.1',
            'title': 'Accuracy, Robustness and Cybersecurity',
            'content': 'High-risk AI systems shall be designed and developed in such a way that they achieve an appropriate level of accuracy, robustness and cybersecurity.'
        },
        {
            'section_code': 'Article17.1',
            'title': 'Human Oversight',
            'content': 'High-risk AI systems shall be designed and developed in such a way that they can be effectively overseen by natural persons.'
        }
    ]
    
    for rule_data in test_rules:
        rule = Rule(
            regulation_id=reg.id,
            section_code=rule_data['section_code'],
            title=rule_data['title'],
            content=rule_data['content'],
            risk_level='high',
            version='1.0'
        )
        db_session.add(rule)
    
    db_session.commit()
    return reg
