# Пример кастомных ключевых слов → код секции
# Этот файл позволяет настраивать маппинг ключевых слов без изменения кода

# Technical Documentation
technical documentation: Article11
documentation: Article11
annex iv: AnnexIV
conformity assessment: AnnexIV.1
ce marking: AnnexIV.1.a
technical file: AnnexIV.2
system architecture: AnnexIV.2.a
dataset description: AnnexIV.2.b

# Risk Management
risk management: Article9.2
risk assessment: Article9.2
risk analysis: Article9.2
foreseeable risks: Article9.2
risk mitigation: Article9.2

# Record-Keeping
record keeping: Article12
audit trail: Article12
system logs: Article12
event logging: Article12

# Human Oversight / Transparency / Accuracy
transparency: Article13
human oversight: Article14
human machine interface: Article14
human control: Article14
meaningful human control: Article14
accuracy: Article15
robustness: Article15
cybersecurity: Article15
resilience: Article15

# Data Governance
data governance: Article10.1
training data: Article10.1
data quality: Article10.1
representative data: Article10.1

# Quality Management
quality management: Article17
quality assurance: Article17
quality control: Article17

# Post-market monitoring
post-market monitoring plan: Article72
