PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?title ?date ?version WHERE {
  ?w cdm:work_id_document "celex:32024R1689"^^xsd:string .
  ?expr cdm:expression_belongs_to_work ?w .
  ?expr cdm:expression_uses_language <http://publications.europa.eu/resource/authority/language/ENG> .
  OPTIONAL { ?expr cdm:expression_title ?title }
  OPTIONAL { ?w cdm:work_date_document ?date }
  OPTIONAL { ?expr cdm:expression_version ?version }
}
ORDER BY DESC(?date)
LIMIT 1
