name: Regulation Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      # Database connection string
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - name: Update regulations
        run: python -m annex4parser update-all --db-url "$DATABASE_URL"
      - name: Sync rules into database
        run: |
          risk-detector sync_rules --db-url "$DATABASE_URL"
